### ISSUE TITLE
Session is not creating.

### ISSUE THREAD

**Issue by Babubsp** [zaidka/genieacs#147] opened 2016-04-06 09:33 UTC
When i execute my CPE code.

i am getting error at ACS.

2016-04-06T09:30:52.839Z - TypeError: Cannot call method 'value' of null
    at parameterValueList (/usr/lib/node_modules/genieacs/lib/soap.js:137:45)
    at acsInform (/usr/lib/node_modules/genieacs/lib/soap.js:292:20)
    at Object.exports.request (/usr/lib/node_modules/genieacs/lib/soap.js:428:39)
    at /usr/lib/node_modules/genieacs/lib/cwmp.js:642:26
    at getSession (/usr/lib/node_modules/genieacs/lib/cwmp.js:573:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/genieacs/lib/cwmp.js:640:12)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:502:13)

6 Apr 15:00:52 - Worker 3372 died (0)
6 Apr 15:00:53 - Worker 3380 listening to 10.226.129.15:7547

As for i know session is not creating... and i dont know how to do that so...

Can anyone suggest me please how to resolve this error.

**Comment by zaidka** [comment] 2016-04-06 21:21
Duplicate of #146.

**Closed by zaidka** 2016-04-06 21:21 UTC
