### ISSUE TITLE
No response from genieacs after informRequest sent

### ISSUE THREAD

**Issue by padhiaryMahendra** [zaidka/genieacs#102] opened 2015-07-10 09:25 UTC
Hi All,
Following error is coming .So please can any one help me to find the solution 
 2015-07-10T05:10:12.082Z - TypeError: Cannot read property 'value' of null
    at parameterValueList (/opt/genieacs/lib/soap.js:137:44)
    at acsInform (/opt/genieacs/lib/soap.js:292:20)
    at Object.exports.request (/opt/genieacs/lib/soap.js:425:39)
    at /opt/genieacs/lib/cwmp.js:638:26
    at getSession (/opt/genieacs/lib/cwmp.js:569:12)
    at IncomingMessage.<anonymous> (/opt/genieacs/lib/cwmp.js:636:12)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11)

**Comment by zaidka** [comment] 2015-07-10 14:31
Also duplicate of #17. Please don't summit the same issue multiple times. Spamming the issue tracker won't get you faster responses.

**Closed by zaidka** 2015-07-10 14:31 UTC
