### ISSUE TITLE
informResponse is not coming form genieacs 

### ISSUE THREAD

**Issue by padhiaryMahendra** [zaidka/genieacs#101] opened 2015-07-10 08:21 UTC
Hi All,
Form my CPE informRequest is sent to ACS but there is no response message coming form ACS .
The error message " TypeError: Cannot read property 'value' of null " is showing in geniacs-cwmp window .And in wireshark internal sever error is displaying .
Can anyone please help me to solve this issue .

Your answer will be appreciated.

**Comment by zaidka** [comment] 2015-07-10 14:30
Duplicate of #17.

**Closed by zaidka** 2015-07-10 14:30 UTC
Labels: duplicate
