### ISSUE TITLE
True/false objects

### ISSUE THREAD

**Issue by Tatermen** [zaidka/genieacs#228] opened 2017-04-10 09:46 UTC
I'm having an issue trying to get GenieACS to work with a TP-Link router, and I'm hitting a problem.

Trying to edit and set any true/false object via the GUI returns a fault - Invalid Arguments. If I tcpdump the traffic, I can see GenieACS sending:

```
<ParameterValueStruct>
    <Name>InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AutoChannelEnable</Name>
    <Value xsi:type="xsd:boolean">false</Value>
</ParameterValueStruct>
```

The TP-Link then sends back a "Invalid Parameter Value' fault code. I suspect this is because the TP-Link is expecting a 0 or 1, and not true or false as if I refresh that same object, it reads:

```
<ParameterValueStruct>
    <Name>InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AutoChannelEnable</Name>
    <Value xsi:type="xsd:boolean">1</Value>
</ParameterValueStruct>
```

Reading the TR069 docs either should work so I believe that this is a TP-Link bug. However, is there a way to have GenieACS use 0/1 instead of true/false?

**Comment by spencerlambert** [comment] 2017-04-10 20:52
What TP-Link device are you using?

**Comment by Tatermen** [comment] 2017-04-11 07:49
It's a TP-Link TD-W9970 router (ADSL/VDSL/Ethernet combo).

**Comment by spencerlambert** [comment] 2017-04-11 23:21
I think this is the place to change `true` or `false to `1` or `0`.

https://github.com/zaidka/genieacs/blob/master/lib/device.js#L34-L38

See if this modification gets the CPE working.
``` js
      case 'xsd:boolean':
        if (typeof parameterValue[0] !== 'boolean') {
          parameterValue[0] = !!JSON.parse(parameterValue[0]);
        }
        parameterValue[0] = parameterValue[0] ? '1' : '0';  // modify true/false to 1 or 0.
        break;
```

**Comment by Tatermen** [comment] 2017-04-12 14:02
Yup, that's done the job.

GenieACS sent:
```
<ParameterValueStruct>
   <Name>InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.AutoChannelEnable</Name>
   <Value xsi:type="xsd:boolean">0</Value>
</ParameterValueStruct>
```

And the response was:
```
<cwmp:SetParameterValuesResponse>
    <Status>0</Status>
</cwmp:SetParameterValuesResponse>
```

I checked the settings on the router and they were changed correctly. I also tested it with a Technicolor TG589vn and it seems to accept either true/false or 1/0 without any problem - so it's definitely a issue with the TP-Link implementation.

**Comment by spencerlambert** [comment] 2017-04-12 15:58
That's good to know. I kinda doubt this change will fly in the main GenieACS code.  I already have device specific items I'm dealing with, so I'm maintaining my own fork.  I'm willing to add an option for switching `true/false` for `1/0` in it, if that helps you out.  Let me know.

**Comment by Tatermen** [comment] 2017-04-12 16:17
Thanks. We're due to get a new batch of routers in on Friday which are a newer model with a newer dated firmware. I'm curious to see if they exhibit the same issue.

**Comment by zaidka** [comment] 2017-04-12 18:52
@spencerlambert, your fix isn't ideal as it's breaking the assumption that boolean parameters are stored internally as boolean type. I'd suggest changing soap.js instead. A PR would certainly be welcome. If you or anyone is willing to submit a PR, please make sure it defaults to true/false and that it can be configured per product class (i.e. pass device ID to config.get()).

**Comment by spencerlambert** [comment] 2017-04-12 19:26
@zaidka If this is an acceptable option, why did you reject the other two CPE related pull requests?  1) the background task watcher and 2) the always sending `NextLevel` as `1`.  Number 2 is in the same class as this true/false issue.

@Tatermen If you need this feature, I'm happy to make the modification and make the pull request.

**Comment by zaidka** [comment] 2017-04-12 23:36
> the background task watcher

Because it's not a trivial change and because a similar solution can be implemented on top of the existing API.

> the always sending NextLevel as 1

Hmm, I wasn't aware you were suggesting that workaround to be merged. I've actually been thinking about implementing a config option(s) for tuning the heuristic used to decide whether to use true or false for nextLevel. It would be nice if we could also tune it per parameter prefix or pattern. I'm not sure how I feel about a simple flag as a workaround for your particular issue. I've never seen that issue before so I'm guessing it's not all that common? The true/false boolean issue is a fairly common issue.

**Comment by spencerlambert** [comment] 2017-04-12 23:46
> I've actually been thinking about implementing a config option(s) for tuning the heuristic

That's good to know.  I'm willing to work on it if one of the tuned items can be to always have NextLevel=1.

**Comment by spencerlambert** [comment] 2017-04-13 00:29
I'm not trying to hijack this thread. I'm trying to understand what makes up an item that is worthy of inclusions. From our discussion on the NextLevel items, it felt like issues pertaining to out of spec CPEs where not legit for a change.  You didn't seem open to a patch, so I never made one. This out-of-spec issue seems too similar, so I assumed that it wasn't an issue that could be handled in the main code.
 
> Because it's not a trivial change

I disagree on this point.  The change was using the existing task watcher, while adding some extra timed event loop calls.  Yes a watcher could be built outside of the server, but I think there is a good case to not leave it up to the client.  Plus there are other people in the community that have a similar issue which it could fix.  Plus, it's the same behavior I've seen in commercial ACS', so it seems like a smart thing to do.

**Comment by spencerlambert** [comment] 2017-04-13 00:40
Another item that lead me to believe that out-of-spec items didn't belong was that my pull request to include "Enabled" and "Disabled" in the bool parser was rejected.  I'm trying to understand how we can all work together.  Right now it feels if you've seen the issue personally, then it's okay to implement an out-of-spec fix.  The issues I'm having that you haven't seen are being rejected.

**Comment by zaidka** [comment] 2017-04-13 03:26
> That's good to know. I'm willing to work on it if one of the tuned items can be to always have NextLevel=1.

Yeah I'm thinking something like 0 = always true, 1 (or 100) = always false, with values in between to adjust the heuristic. I have to warn you though it's not going to be fun. Let's just say I'm not proud of that part of the code :) And the problem is deceptively complex.

> I'm trying to understand what makes up an item that is worthy of inclusions. From our discussion on the NextLevel items, it felt like issues pertaining to out of spec CPEs where not legit for a change.

I don't know, I guess I judge it on a case by case basis. If the change is simple and the issue common enough then why not.

> I disagree on this point. The change was using the existing task watcher, while adding some extra timed event loop calls.

It was doing background work *after* the response is sent and I don't feel good about that. When I said a trivial change I wasn't only talking in terms of lines of code but also what it's doing.

> Plus, it's the same behavior I've seen in commercial ACS', so it seems like a smart thing to do.

Though I hate that argument, I get what you're saying. I'm open to implementing this as a proper generic feature, rather than a specific workaround. By generic feature I mean the ability to schedule future informs through the API and from scripts (either using a background process that sends connection requests, or using ScheduleInform method if supported). And then that feature can be utilized to work around the particular problem with your device.

> include "Enabled" and "Disabled" in the bool parser was rejected

These are not valid boolean values while 1 and 0 are valid in the specs.

> Right now it feels if you've seen the issue personally, then it's okay to implement an out-of-spec fix.

Not necessarily. I also maintain my separate forks with patches for issues like this.

**Comment by spencerlambert** [comment] 2017-04-13 04:22
> Yeah I'm thinking something like 0 = always true, 1 (or 100) = always false, with values in between to adjust the heuristic. 

Are you thinking in-between values, like 50, do something different?

> It would be nice if we could also tune it per parameter prefix or pattern.

The swapping out true/false for 1/0 seems to fit under this.  I'm seeing the potential to address both issues (NextLevel and true/false) with the same feature. 

> I have to warn you though it's not going to be fun.

If you can guide me a little, I don't mind making a go of it.  First I'd like to understand more on how you see the tuning config part working.  What would the config look like for the user?

**Comment by zaidka** [comment] 2017-04-13 05:54
> Are you thinking in-between values, like 50, do something different?

Yes, like the current implementation where it tries to intelligently decide which would be more efficient given a set of declarations and what it knows about the data models.

> If you can guide me a little, I don't mind making a go of it. First I'd like to understand more on how you see the tuning config part working. What would the config look like for the user?

Something like a single numeric value representing the relative "preference" for nextLevel. Lower values mean prefer fewer RPC requests and higher values mean prefer lower bandwidth and DB use (by not fetching params that aren't needed). This becomes even more useful if we can specify this tuning value per parameter prefix. So for example you can tell it to prefer fewer requests for params under Device.ManagementServer because that subtree is small, and prefer lower bandwidth and RAM/storage use for params under Device.WANDevice because that subtree is huge and we only need a few params from that subtree. This is a long discussion so let's take it to the mailing list please.

**Closed** 2017-06-07 15:52 UTC

**Comment by mths0x5f** [comment] 2018-02-19 02:38
I'm facing this exact issue with ~50k TD-W9970 devices, in GenieACS v1.1.1. Is there any patch for this?

**Comment by spencerlambert** [comment] 2018-02-19 02:54
This is what I did to fix it: https://github.com/spencerlambert/genieacs/commit/3a738c1e2dce0fa26cca118a52abb71e5f48c6b5

**Comment by Tatermen** [comment] 2018-02-19 10:53
@mths0x5f We've been using the @spencerlambert fix for 9 months now without any issue. 

Ultimately the issue is caused by TP-Link not following the CWMP standards properly, and I was not able to get them to take it seriously as we're not a big purchaser (<500 devices). Maybe you could try reporting it to them - they may take it more seriously from someone with 50,000 devices.

**Comment by mths0x5f** [comment] 2018-02-19 13:21
@spencerlambert, @Tatermen thank you! Yep, we are discussing internally to report to TP-LINK. The problem is the current number of deployed devices to costumers and the time required to these changes if they would make it at all.
