### ISSUE TITLE
Problem in Getting New device Registered

### ISSUE THREAD

**Issue by shubhammanglik** [zaidka/genieacs#188] opened 2016-11-17 07:23 UTC
Hello,

From your installation documents https://genieacs.com/docs/ First I have install genieacs by using this command git clone **https://github.com/zaidka/genieacs.git --branch v1.0** and it was successfully get installed and CPE device is also get registered but was facing some problem in this.

Then I try to install master or stable branch  by using this **https://github.com/zaidka/genieacs.git**,it is perfectly installed.But in this master branch,there is problem I am facing is that CPE device is unable to get registered. I have done some research and do some changes in the code helps me to get registered the CPE device,but on GUI it is showing blank data for registered device while  for same CPE device **in old branch of genieacs** it is giving right picture on GUI.Below is the GUI image with master branch

![screenshot](https://cloud.githubusercontent.com/assets/22903927/20379924/c42bc7d0-acc4-11e6-9af6-c24b509d02eb.png)

If you have time please help me out what am I doing wrong.

**Comment by zaidka** [comment] 2016-11-17 09:25
Feeling so nostalgic looking at that screenshot :)

Unless you're seeing a fault or a crash, this is not a bug, it's a feature. In v1.1 Genie will only fetch the parameters it needs rather than the entire data model. You simply need to add a preset to refresh those parameters. Or fetch the root parameter (e.g. InternetGatewayDevice) to have it fetch everything just like in v1.0.

**Comment by mberniz** [comment] 2016-11-21 15:28
Hi Zaid,

I have followed your instructions and created a preset to reflresh InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID without any precondition or event.

I wanted to do that in order to gather the SSID because it is not being fetch initially. But I find that it fetchs the whole tree. I assume this is not effective as I only want to work with a couple dozens parameters. 

How can I prevent refreshing the whole tree?

Thanks in advance

**Comment by mberniz** [comment] 2016-11-21 22:24
I answer myself.

It works as expected, the parameters tree is completely downloaded but not the values, only the ones setup in the preset are refreshed.

Thanks

**Comment by developer-Sh** [comment] 2016-12-19 09:31
Does GenieACS provide the handling of Alarms generated from CPE devices ??

**Comment by DrumSergio** [comment] 2017-02-03 23:58
How could you fetch the root parameter, @zaidka ? I'm interested in some examples. Maybe you've yet documented them in the release for the beta... :) 

You can close this issue...

**Closed** 2017-03-11 23:56 UTC
