### ISSUE TITLE
Error: "Could not locate the bindings file."

### ISSUE THREAD

**Issue by ramtinkazemi** [zaidka/genieacs#67] opened 2015-02-11 01:20 UTC
I installed GeniACS on my server (CentOS 6.6, 32 bit) with no error message. I have also installed MongoDB, Redis, and Node.js successfully and all working properly. However, I get the following error message when I issue the command "genieacs-cwmp":

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/build/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Debug/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/build/Release/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/out/Debug/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/Debug/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/out/Release/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/Release/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/build/default/xmljs.node
 → /usr/lib/node_modules/genieacs/node_modules/libxmljs/compiled/0.10.33/linux/ia32/xmljs.node
    at bindings (/usr/lib/node_modules/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/genieacs/node_modules/libxmljs/index.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
8 Feb 23:34:06 - Worker 13129 died (8)
8 Feb 23:34:06 - Worker 13133 died (8)

**Comment by zaidka** [comment] 2015-02-11 16:25
Duplicate of #56.

**Closed by zaidka** 2015-02-11 16:25 UTC
Labels: duplicate
