### ISSUE TITLE
problem with factory reset

### ISSUE THREAD

**Issue by LuCe86** [zaidka/genieacs#81] opened 2015-04-21 09:30 UTC
Hi everyone
I have a problem, I want to add a factory reset as task to my cpe after the download (and subsequent reboot) of a new firmware.
When I try, I can’t do this because the cpe doesn’t complete the transfer, the factory reset task starts after the download is completed.
Is it possible delay the second task? or is it possible to tie a task when it received a specific method (eg transfer complete)?
thank you

**Comment by LuCe86** [comment] 2015-04-21 16:22
I'm trying in this way:

in
genieacs/lib/cwmp.js
 
if (__indexOf.call(cwmpRequest.methodRequest.event, 'M DOWNLOAD') >= 0) {
    db.tasks.insert({"_id" : ObjectId(), "name" : "factoryReset", "device": currentRequest.session.deviceId, "timestamp" : ISODate()}, 
	function(err, removed) {
      if (err) {
        throw err;
      }
    });
  }

 genieacs/lib/cwmp.coffee 
if 'M DOWNLOAD' in cwmpRequest.methodRequest.event
    db.tasks.insert({"_id" : ObjectId(), "name" : "factoryReset", "device": currentRequest.session.deviceId, "timestamp" : ISODate()}, (err, removed) ->
      throw err if err
    )
 
is it correct?

thank you

**Comment by zaidka** [comment] 2015-04-21 16:32
You don't need to patch the code. You can set the time of the factory reset task a few seconds into the future so it's not picked up until after the upgrade is done.

BTW, I'd suggest using the mailing list (lists.genieacs.com). You'll probably get quicker responses and suggestions from the community. I'm marking this as closed since it's not a bug report or feature request.

**Closed by zaidka** 2015-04-21 16:32 UTC

**Comment by LuCe86** [comment] 2015-04-22 06:33
Hi Zaid AbdullaVery special thanks for the quickly answer.Can you explain me how I can set the time of factory reset task?and the solution to tie the event factory reset on receipt of a specific method (M Downoload or 7 Transfer Complete) is not practicable?
thanks in advancebest regards

Luciano

Date: Tue, 21 Apr 2015 09:32:53 -0700

**Comment by zaidka** [comment] 2015-04-24 06:32
You need to set a timestamp parameter in the task object. I think the API Reference in the wiki has an example.

It's not yet possible to tie tasks to CPE events. But this is one of the features I'm considering for future releases.
