### ISSUE TITLE
Die service

### ISSUE THREAD

**Issue by bogdik** [zaidka/genieacs#114] opened 2015-10-07 10:30 UTC
7 Oct 13:26:15 - A8F94B-TAU%2D2M%2EIP-VI39016250: Inform (1 BOOT); retry count 0
7 Oct 13:26:15 - A8F94B-TAU%2D2M%2EIP-VI39016250: New device registered
7 Oct 13:26:15 - A8F94B-TAU%2D2M%2EIP-VI39016250: Started task refreshObject(5614f34743f9bb0130131e83)
2015-10-07T10:26:16.235Z - TypeError: Cannot call method 'value' of null
    at parameterValueList (/opt/genieacs-071015/lib/soap.js:137:45)
    at cpeGetParameterValuesResponse (/opt/genieacs-071015/lib/soap.js:190:20)
    at Object.exports.request (/opt/genieacs-071015/lib/soap.js:445:40)
    at /opt/genieacs-071015/lib/cwmp.js:642:26
    at /opt/genieacs-071015/lib/cwmp.js:579:12
    at b (domain.js:183:18)
    at try_callback (/opt/genieacs-071015/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/opt/genieacs-071015/node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (/opt/genieacs-071015/node_modules/redis/index.js:321:14)
    at HiredisReplyParser.EventEmitter.emit (events.js:95:17)

7 Oct 13:26:16 - Worker 12289 died (0)

tree into base:
{
  "_id": "A8F94B-TAU%2D2M%2EIP-VI39016250",
  "_registered": ISODate("2015-10-07T10:26:15.588Z"),
  "_deviceId": {
    "_Manufacturer": "Eltex",
    "_OUI": "A8F94B",
    "_ProductClass": "TAU-2M.IP",
    "_SerialNumber": "VI39016250"
  },
  "_lastInform": ISODate("2015-10-07T10:27:16.923Z"),
  "InternetGatewayDevice": {
    "WANDevice": {
      "1": {
        "WANConnectionDevice": {
          "1": {
            "WANIPConnection": {
              "1": {
                "ExternalIPAddress": {
                  "_value": "0.75.0.0",
                  "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
                  "_type": "xsd:string"
                }
              }
            }
          }
        }
      }
    },
    "ManagementServer": {
      "ParameterKey": {
        "_value": "",
        "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
        "_type": "xsd:string"
      },
      "ConnectionRequestURL": {
        "_value": "http://10.52.2.60:9998",
        "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
        "_type": "xsd:string"
      }
    },
    "DeviceInfo": {
      "ProvisioningCode": {
        "_value": "",
        "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
        "_type": "xsd:string"
      },
      "SoftwareVersion": {
        "_value": "#1.12.0",
        "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
        "_type": "xsd:string"
      },
      "HardwareVersion": {
        "_value": "1.2",
        "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
        "_type": "xsd:string"
      },
      "SpecVersion": {
        "_value": "1.0",
        "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
        "_type": "xsd:string"
      }
    },
    "DeviceSummary": {
      "_value": "InternetGatewayDevice:1.0[](Baseline:1)",
      "_timestamp": ISODate("2015-10-07T10:27:16.923Z"),
      "_type": "xsd:string"
    }
  }
}

**Comment by zaidka** [comment] 2015-10-07 22:53
Duplicate of #17.

**Closed by zaidka** 2015-10-07 22:53 UTC
Labels: duplicate
