### ISSUE TITLE
Error starting genieacs-cwmp

### ISSUE THREAD

**Issue by KiNGKiMO** [zaidka/genieacs#164] opened 2016-07-26 19:37 UTC
Hello,

looks like the latest .git is bugged, any ideas?

/root/genieacs/lib/device.js:55
          throw new Error(`Parameter value type "${parameterValue[1]}" not rec
                          ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/genieacs/lib/session.js:29:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
26 Jul 21:35:28 - Worker 27502 died (8)

**Comment by zaidka** [comment] 2016-07-26 19:44
You need to upgrade your Node.js to version 4.4.

**Comment by KiNGKiMO** [comment] 2016-07-26 20:07
Updating as follows:-
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs


Now geeting a new error:-

Error: /root/genieacs/node_modules/libxmljs/build/Release/xmljs.node: undefined symbol: _ZN2v82V837Adjust│
AmountOfExternalAllocatedMemoryEl                                                                        │
    at Error (native)                                                                                    │
    at Object.Module._extensions..node (module.js:434:18)                                                │
    at Module.load (module.js:343:32)                                                                    │
    at Function.Module._load (module.js:300:12)                                                          │
    at Module.require (module.js:353:17)                                                                 │
    at require (internal/module.js:12:17)                                                                │
    at bindings (/root/genieacs/node_modules/libxmljs/node_modules/bindings/bindings.js:76:44)           │
    at Object.<anonymous> (/root/genieacs/node_modules/libxmljs/lib/bindings.js:1:99)                    │
    at Module._compile (module.js:409:26)                                                                │
    at Object.Module._extensions..js (module.js:416:10)                                                  │
26 Jul 22:06:29 - Worker 29467 died (1)

**Comment by zaidka** [comment] 2016-08-26 07:23
Looks like you didn't reinstall dependencies after upgrading node. Will close this but feel free to reopen if the issue persists.

**Closed by zaidka** 2016-08-26 07:23 UTC

**Comment by yilcheng** [comment] 2016-09-07 06:14
Hi sir, it seems I encountered the same problems and I follow the instruction to update nodejs, then its version is v4.5.0 now. but the problem is still the same, I can't start geniceacs-cwmp, could you help to check it? Thanks.

--
/root/genieacs/lib/device.js:55
throw new Error(`Parameter value type "${parameterValue[1]}" not rec
^
SyntaxError: Unexpected token ILLEGAL
at Module._compile (module.js:439:25)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:12)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object. (/root/genieacs/lib/session.js:29:10)
at Module._compile (module.js:456:26)
at Object.Module._extensions..js (module.js:474:10)
at Module.load (module.js:356:32)
at Function.Module._load (module.js:312:32)
26 Jul 21:35:28 - Worker 2811 died (8)
